[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiosmtplib>=4.0.1",
    "email-validator>=2.2.0",
    "jinja2>=3.1.6",
    "pydantic-settings>=2.10.1",
    "stripe>=12.3.0",
]
